///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace com.edgewords.specflow.nunit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the com_edgewords_specflow_nunitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("0dc356a7-8a4f-481c-8507-54f330156e85")]
    public partial class com_edgewords_specflow_nunitRepository : RepoGenBaseFolder
    {
        static com_edgewords_specflow_nunitRepository instance = new com_edgewords_specflow_nunitRepository();
        com_edgewords_specflow_nunitRepositoryFolders.AutomatedToolsTestSiteAppFolder _automatedtoolstestsite;
        com_edgewords_specflow_nunitRepositoryFolders.FormsAppFolder _forms;

        /// <summary>
        /// Gets the singleton class instance representing the com_edgewords_specflow_nunitRepository element repository.
        /// </summary>
        [RepositoryFolder("0dc356a7-8a4f-481c-8507-54f330156e85")]
        public static com_edgewords_specflow_nunitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public com_edgewords_specflow_nunitRepository() 
            : base("com_edgewords_specflow_nunitRepository", "/", null, 0, false, "0dc356a7-8a4f-481c-8507-54f330156e85", ".\\RepositoryImages\\com_edgewords_specflow_nunitRepository0dc356a7.rximgres")
        {
            _automatedtoolstestsite = new com_edgewords_specflow_nunitRepositoryFolders.AutomatedToolsTestSiteAppFolder(this);
            _forms = new com_edgewords_specflow_nunitRepositoryFolders.FormsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0dc356a7-8a4f-481c-8507-54f330156e85")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AutomatedToolsTestSite folder.
        /// </summary>
        [RepositoryFolder("3e0932e9-350d-4804-8953-3a5a256a4be8")]
        public virtual com_edgewords_specflow_nunitRepositoryFolders.AutomatedToolsTestSiteAppFolder AutomatedToolsTestSite
        {
            get { return _automatedtoolstestsite; }
        }

        /// <summary>
        /// The Forms folder.
        /// </summary>
        [RepositoryFolder("43c57489-dc73-480b-8069-08b3a3a8912e")]
        public virtual com_edgewords_specflow_nunitRepositoryFolders.FormsAppFolder Forms
        {
            get { return _forms; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class com_edgewords_specflow_nunitRepositoryFolders
    {
        /// <summary>
        /// The AutomatedToolsTestSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("3e0932e9-350d-4804-8953-3a5a256a4be8")]
        public partial class AutomatedToolsTestSiteAppFolder : RepoGenBaseFolder
        {
            com_edgewords_specflow_nunitRepositoryFolders.SomeUlTagFolder _someultag;
            RepoItemInfo _titleInfo;

            /// <summary>
            /// Creates a new AutomatedToolsTestSite  folder.
            /// </summary>
            public AutomatedToolsTestSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AutomatedToolsTestSite", "/dom[@caption='Automated Tools Test Site']", parentFolder, 30000, null, false, "3e0932e9-350d-4804-8953-3a5a256a4be8", "")
            {
                _someultag = new com_edgewords_specflow_nunitRepositoryFolders.SomeUlTagFolder(this);
                _titleInfo = new RepoItemInfo(this, "title", ".//div[#'right-column']/h1[@innertext='Automated Tools Test Site']", 30000, null, "3613c1a8-0480-4077-a74e-b54f71215bfc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3e0932e9-350d-4804-8953-3a5a256a4be8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e0932e9-350d-4804-8953-3a5a256a4be8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The title item.
            /// </summary>
            [RepositoryItem("3613c1a8-0480-4077-a74e-b54f71215bfc")]
            public virtual Ranorex.H1Tag title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The title item info.
            /// </summary>
            [RepositoryItemInfo("3613c1a8-0480-4077-a74e-b54f71215bfc")]
            public virtual RepoItemInfo titleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The SomeUlTag folder.
            /// </summary>
            [RepositoryFolder("6ad0c047-fd56-4689-9560-41aa29f3acc2")]
            public virtual com_edgewords_specflow_nunitRepositoryFolders.SomeUlTagFolder SomeUlTag
            {
                get { return _someultag; }
            }
        }

        /// <summary>
        /// The SomeUlTagFolder folder.
        /// </summary>
        [RepositoryFolder("6ad0c047-fd56-4689-9560-41aa29f3acc2")]
        public partial class SomeUlTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _basichtmlInfo;
            RepoItemInfo _formsInfo;
            RepoItemInfo _homeInfo;

            /// <summary>
            /// Creates a new SomeUlTag  folder.
            /// </summary>
            public SomeUlTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeUlTag", ".//div[#'menu']/ul", parentFolder, 30000, null, false, "6ad0c047-fd56-4689-9560-41aa29f3acc2", "")
            {
                _basichtmlInfo = new RepoItemInfo(this, "BasicHTML", ".//span[@innertext='Basic HTML']", 30000, null, "969b1e55-29a8-44bf-acc6-82d6564286ce");
                _formsInfo = new RepoItemInfo(this, "Forms", ".//span[@innertext='Forms']", 30000, null, "610fbd19-e61f-44e5-b282-e2184b0b23fa");
                _homeInfo = new RepoItemInfo(this, "Home", ".//span[@innertext='Home']", 30000, null, "b52bedee-37a1-494b-ab45-ff6f2d7323cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ad0c047-fd56-4689-9560-41aa29f3acc2")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ad0c047-fd56-4689-9560-41aa29f3acc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BasicHTML item.
            /// </summary>
            [RepositoryItem("969b1e55-29a8-44bf-acc6-82d6564286ce")]
            public virtual Ranorex.SpanTag BasicHTML
            {
                get
                {
                    return _basichtmlInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BasicHTML item info.
            /// </summary>
            [RepositoryItemInfo("969b1e55-29a8-44bf-acc6-82d6564286ce")]
            public virtual RepoItemInfo BasicHTMLInfo
            {
                get
                {
                    return _basichtmlInfo;
                }
            }

            /// <summary>
            /// The Forms item.
            /// </summary>
            [RepositoryItem("610fbd19-e61f-44e5-b282-e2184b0b23fa")]
            public virtual Ranorex.SpanTag Forms
            {
                get
                {
                    return _formsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Forms item info.
            /// </summary>
            [RepositoryItemInfo("610fbd19-e61f-44e5-b282-e2184b0b23fa")]
            public virtual RepoItemInfo FormsInfo
            {
                get
                {
                    return _formsInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("b52bedee-37a1-494b-ab45-ff6f2d7323cc")]
            public virtual Ranorex.SpanTag Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("b52bedee-37a1-494b-ab45-ff6f2d7323cc")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }
        }

        /// <summary>
        /// The FormsAppFolder folder.
        /// </summary>
        [RepositoryFolder("43c57489-dc73-480b-8069-08b3a3a8912e")]
        public partial class FormsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _homeInfo;

            /// <summary>
            /// Creates a new Forms  folder.
            /// </summary>
            public FormsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Forms", "/dom[@caption='Forms']", parentFolder, 30000, null, false, "43c57489-dc73-480b-8069-08b3a3a8912e", "")
            {
                _homeInfo = new RepoItemInfo(this, "Home", ".//div[#'menu']/ul//span[@innertext='Home']", 30000, null, "bdef04fe-17da-4f1c-973f-d58d7f2f17a4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("43c57489-dc73-480b-8069-08b3a3a8912e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("43c57489-dc73-480b-8069-08b3a3a8912e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("bdef04fe-17da-4f1c-973f-d58d7f2f17a4")]
            public virtual Ranorex.SpanTag Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("bdef04fe-17da-4f1c-973f-d58d7f2f17a4")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}